#############################################################################
# Makefile for building: ept
# Generated by qmake (2.01a) (Qt 4.8.4) on: Wed Jan 15 18:53:39 2014
# Project:  EPT.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile EPT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++0x -DDEBUG -DLINUX -g -DGLEW -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I../Dodge/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L../Dodge/lib -L/usr/lib/i386-linux-gnu -lDodge -lX11 -lGL -lGLEW -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Application.cpp \
		Common.cpp \
		EptObject.cpp \
		Exporter.cpp \
		Importer.cpp \
		main.cpp \
		MainWindow.cpp \
		MapSettings.cpp \
		ObjectContainer.cpp \
		WgtMapSettings.cpp \
		WgtXmlTreeView.cpp moc_MainWindow.cpp \
		moc_WgtMapSettings.cpp \
		moc_WgtXmlTreeView.cpp
OBJECTS       = Application.o \
		Common.o \
		EptObject.o \
		Exporter.o \
		Importer.o \
		main.o \
		MainWindow.o \
		MapSettings.o \
		ObjectContainer.o \
		WgtMapSettings.o \
		WgtXmlTreeView.o \
		moc_MainWindow.o \
		moc_WgtMapSettings.o \
		moc_WgtXmlTreeView.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EPT.pro
QMAKE_TARGET  = ept
DESTDIR       = 
TARGET        = ept

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: EPT.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile EPT.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EPT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ept1.0.0 || $(MKDIR) .tmp/ept1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ept1.0.0/ && $(COPY_FILE) --parents Application.hpp Common.hpp EptObject.hpp Exporter.hpp Importer.hpp MainWindow.hpp MapSettings.hpp ObjectContainer.hpp WgtMapSettings.hpp WgtXmlTreeView.hpp .tmp/ept1.0.0/ && $(COPY_FILE) --parents Application.cpp Common.cpp EptObject.cpp Exporter.cpp Importer.cpp main.cpp MainWindow.cpp MapSettings.cpp ObjectContainer.cpp WgtMapSettings.cpp WgtXmlTreeView.cpp .tmp/ept1.0.0/ && (cd `dirname .tmp/ept1.0.0` && $(TAR) ept1.0.0.tar ept1.0.0 && $(COMPRESS) ept1.0.0.tar) && $(MOVE) `dirname .tmp/ept1.0.0`/ept1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ept1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_WgtMapSettings.cpp moc_WgtXmlTreeView.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_WgtMapSettings.cpp moc_WgtXmlTreeView.cpp
moc_MainWindow.cpp: ObjectContainer.hpp \
		EptObject.hpp \
		MainWindow.hpp
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) MainWindow.hpp -o moc_MainWindow.cpp

moc_WgtMapSettings.cpp: MapSettings.hpp \
		WgtMapSettings.hpp
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) WgtMapSettings.hpp -o moc_WgtMapSettings.cpp

moc_WgtXmlTreeView.cpp: WgtXmlTreeView.hpp
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) WgtXmlTreeView.hpp -o moc_WgtXmlTreeView.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Application.o: Application.cpp Application.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Application.o Application.cpp

Common.o: Common.cpp Common.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Common.o Common.cpp

EptObject.o: EptObject.cpp Common.hpp \
		EptObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EptObject.o EptObject.cpp

Exporter.o: Exporter.cpp ObjectContainer.hpp \
		EptObject.hpp \
		Exporter.hpp \
		MapSettings.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Exporter.o Exporter.cpp

Importer.o: Importer.cpp Importer.hpp \
		MapSettings.hpp \
		ObjectContainer.hpp \
		EptObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Importer.o Importer.cpp

main.o: main.cpp Application.hpp \
		MainWindow.hpp \
		ObjectContainer.hpp \
		EptObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.hpp \
		ObjectContainer.hpp \
		EptObject.hpp \
		WgtXmlTreeView.hpp \
		WgtMapSettings.hpp \
		MapSettings.hpp \
		Common.hpp \
		Importer.hpp \
		Exporter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MapSettings.o: MapSettings.cpp MapSettings.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MapSettings.o MapSettings.cpp

ObjectContainer.o: ObjectContainer.cpp Common.hpp \
		ObjectContainer.hpp \
		EptObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectContainer.o ObjectContainer.cpp

WgtMapSettings.o: WgtMapSettings.cpp WgtMapSettings.hpp \
		MapSettings.hpp \
		EptObject.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WgtMapSettings.o WgtMapSettings.cpp

WgtXmlTreeView.o: WgtXmlTreeView.cpp WgtXmlTreeView.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WgtXmlTreeView.o WgtXmlTreeView.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_WgtMapSettings.o: moc_WgtMapSettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WgtMapSettings.o moc_WgtMapSettings.cpp

moc_WgtXmlTreeView.o: moc_WgtXmlTreeView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WgtXmlTreeView.o moc_WgtXmlTreeView.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

